version: '3.3'
services:
  api:
    image: golang:1.10
    container_name: 'api'
    depends_on:
      - 'mongo'
    command: go test
    volumes:
      - ./:/go/src/github.com/kypseli/todo-api:rw
    working_dir: /go/src/github.com/kypseli/todo-api
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'